create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null check (role in ('ADMIN', 'USER')),
  department_id bigint references public.departments(id) on delete set null
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  bil_mesyuarat text not null,
  tarikh_mesyuarat date not null,
  department_id bigint not null references public.departments(id) on delete cascade,
  minit_path text,
  submission_method text,
  is_locked integer not null default 0,
  unlock_requested integer not null default 0,
  unlock_rejected integer not null default 0,
  delete_requested integer not null default 0,
  delete_rejected integer not null default 0,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.issues (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(id) on delete cascade,
  category text not null,
  is_from_previous integer not null default 0,
  title text not null,
  status text not null check (status in ('Selesai', 'Belum Selesai')),
  responsible_officer text,
  updated_at timestamptz not null default now()
);

insert into public.departments (name)
values ('HQ'), ('IT'), ('HR'), ('FINANCE')
on conflict (name) do nothing;

insert into public.categories (name)
values ('Kebajikan'), ('Perjawatan'), ('Kewangan'), ('Infrastruktur'), ('Lain-lain')
on conflict (name) do nothing;
