services:
  - type: web
    name: embj
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:render
    healthCheckPath: /api/health
    autoDeploy: true
